In [4]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

How many dimension on this array

In [14]:
a.ndim

2

itemsize shows us bytesize of the element of array

In [15]:
a.itemsize

4

Current datatype

In [20]:
a.dtype

dtype('int32')

Float type datatype

In [7]:
b=np.array([[1.5,2.5],[3,1.9]])
print(b.dtype)
print(b.itemsize)

float64
8


Range function.
arrange(a,b,c) then c means how many steps it jumping

In [10]:
print(np.arange(1,10))
print(np.arange(1,10,2))

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


Linspace() function.Create linear sequence of numbers

In [11]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

reshape() function.ravel() function which makes any dimension array to 1D array

In [22]:
c=np.array([[1,2,3],[4,5,6]])
print(c.shape)
print(c.reshape(3,2))
print(c.ravel())
print(c)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


max(),min(),sum(),sqrt(),std() function

In [32]:
print(c)
print(c.max())
print(c.min())
print(c.sum(axis=0))    #axis=0 means columns 
print(c.sum(axis=1))    #axis=1 means rows
print(np.sqrt(c))
print(c.std())

[[1 2 3]
 [4 5 6]]
6
1
[5 7 9]
[ 6 15]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
1.707825127659933


Some mathematics

In [37]:
d=np.array([[1,2],[3,4]])
e=np.array([[5,6],[7,8]])
print(d+e)
print(d-e)
print(d*e)
print(d/e)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
