In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Indexing and Slicing

In [ ]:
print(a[1,2])
print(a[0:2,2])
print(a[-1,0:2])
print(a[:,1:])

6
[3 6]
[7 8]


Iterate through array

In [ ]:
for row in a:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [26]:
for cell in a.flat:
    print(cell)

1
2
3
4
5
6
7
8
9


Sticking together two array

In [43]:
a=np.arange(6).reshape(2,3)
b=np.arange(6,12).reshape(2,3)

print(np.vstack([a,b])) #extra bracket needed,beacuse vstack function can take one argument,so that we need to pass our argument as a list[] or tupples()
print(np.hstack((a,b)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [44]:
a=np.arange(30).reshape(2,15)
ans=np.hsplit(a,3)
print(ans[0])
print(ans[1])
print(ans[2])

[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [47]:
ans=np.vsplit(a,2)
ans

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

Indexing with boolean array

In [52]:
a=np.arange(12).reshape(3,4)

b=a<5
b

a[b]
a[b]=21
a

array([[21, 21, 21, 21],
       [21,  5,  6,  7],
       [ 8,  9, 10, 11]])