In [24]:
import numpy as np

Running for loop

In [2]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


Same thing we can do by using flatten() function

In [5]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


Same thing we can also do by using nditer() function 

In [9]:
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [10]:
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


Using flags

In [13]:
for x in np.nditer(a,order='f',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


By op flags we can modify the elements

In [22]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x+x

a

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44]])

iterate two arrays

In [29]:
b=np.arange(12,15).reshape(3,1)
b

array([[12],
       [13],
       [14]])

In [31]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 12
4 12
8 12
12 12
16 13
20 13
24 13
28 13
32 14
36 14
40 14
44 14
